# Generated by Django 5.2.11 on 2026-03-24 08:03

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('products', '0001_initial'),
        ('vendors', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ASN',
            fields=[
                ('asn_id', models.CharField(editable=False, max_length=10, primary_key=True, serialize=False)),
                ('asn_number', models.CharField(max_length=50, unique=True)),
                ('shipment_date', models.DateField()),
                ('expected_arrival_date', models.DateField()),
                ('vehicle_num', models.CharField(max_length=13)),
                ('driver_name', models.CharField(max_length=25)),
                ('driver_phone', models.CharField(max_length=15)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('vendor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='asn_vendor', to='vendors.vendor')),
            ],
        ),
        migrations.CreateModel(
            name='ASNItem',
            fields=[
                ('asn_item_id', models.CharField(editable=False, max_length=20, primary_key=True, serialize=False)),
                ('expected_quantity', models.IntegerField()),
                ('shipped_quantity', models.IntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('asn', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='Inventory.asn')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.product')),
            ],
        ),
        migrations.CreateModel(
            name='GRN',
            fields=[
                ('grn_id', models.CharField(editable=False, max_length=10, primary_key=True, serialize=False)),
                ('grn_number', models.CharField(max_length=50, unique=True)),
                ('receipt_date', models.DateField()),
                ('status', models.CharField(choices=[('RECEIVED', 'Received by Supervisor'), ('QC_PENDING', 'QC Pending'), ('COMPLETED', 'Completed')], default='RECEIVED', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('asn', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Inventory.asn')),
                ('qc_verified_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='grn_verified', to=settings.AUTH_USER_MODEL)),
                ('received_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='grn_received', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='GRNItem',
            fields=[
                ('grn_item_id', models.CharField(editable=False, max_length=15, primary_key=True, serialize=False)),
                ('received_quantity', models.IntegerField()),
                ('accepted_quantity', models.IntegerField(default=0)),
                ('rejected_quantity', models.IntegerField(default=0)),
                ('qc_status', models.CharField(choices=[('Pending', 'Pending'), ('Completed', 'Completed')], default='Pending', max_length=15)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('grn', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='Inventory.grn')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.product')),
            ],
        ),
        migrations.CreateModel(
            name='Inventory',
            fields=[
                ('inventory_id', models.CharField(editable=False, max_length=10, primary_key=True, serialize=False)),
                ('zone_name', models.CharField(max_length=3)),
                ('shelf_name', models.CharField(max_length=3)),
                ('rack_name', models.CharField(max_length=3)),
                ('bin_name', models.CharField(max_length=3)),
                ('quantity', models.IntegerField(default=0)),
                ('last_update', models.DateTimeField(auto_now=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inventories', to='products.product')),
            ],
        ),
        migrations.CreateModel(
            name='PurchaseOrder',
            fields=[
                ('po_id', models.CharField(editable=False, max_length=10, primary_key=True, serialize=False)),
                ('order_quantity', models.IntegerField()),
                ('total_amount', models.IntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('vendor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vendors.vendor')),
            ],
        ),
        migrations.AddField(
            model_name='grn',
            name='po',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Inventory.purchaseorder'),
        ),
        migrations.AddField(
            model_name='asn',
            name='po',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='asn_po', to='Inventory.purchaseorder'),
        ),
        migrations.CreateModel(
            name='PurchaseRequest',
            fields=[
                ('pr_id', models.CharField(editable=False, max_length=10, primary_key=True, serialize=False)),
                ('requested_quantity', models.IntegerField()),
                ('total_amount', models.IntegerField()),
                ('status', models.CharField(choices=[('Pending', 'Pending'), ('Manager Approved', 'Manager Approved'), ('Finance Pending', 'Finance Pending'), ('Approved', 'Approved'), ('Rejected', 'Rejected')], default='Pending', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.product')),
                ('vendor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vendors.vendor')),
            ],
        ),
        migrations.AddField(
            model_name='purchaseorder',
            name='pr',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='Inventory.purchaserequest'),
        ),
    ]
