# Generated by Django 6.0.1 on 2026-03-12 16:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Inventory',
            fields=[
                ('inventory_id', models.CharField(editable=False, max_length=10, primary_key=True, serialize=False)),
                ('zone_name', models.CharField(max_length=3)),
                ('shelf_name', models.CharField(max_length=3)),
                ('rack_name', models.CharField(max_length=3)),
                ('bin_name', models.CharField(max_length=3)),
                ('quantity', models.IntegerField(default=0)),
                ('last_update', models.DateTimeField(auto_now=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inventories', to='products.product')),
            ],
        ),
        migrations.CreateModel(
            name='PurchaseRequest',
            fields=[
                ('pr_id', models.CharField(editable=False, max_length=10, primary_key=True, serialize=False)),
                ('requested_quantity', models.IntegerField()),
                ('status', models.CharField(default='Pending', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.product')),
            ],
        ),
    ]
