# Generated by Django 5.2.11 on 2026-03-13 09:01

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('products', '0001_initial'),
        ('vendors', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Inventory',
            fields=[
                ('inventory_id', models.CharField(editable=False, max_length=10, primary_key=True, serialize=False)),
                ('zone_name', models.CharField(max_length=3)),
                ('shelf_name', models.CharField(max_length=3)),
                ('rack_name', models.CharField(max_length=3)),
                ('bin_name', models.CharField(max_length=3)),
                ('quantity', models.IntegerField(default=0)),
                ('last_update', models.DateTimeField(auto_now=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inventories', to='products.product')),
            ],
        ),
        migrations.CreateModel(
            name='PurchaseRequest',
            fields=[
                ('pr_id', models.CharField(editable=False, max_length=10, primary_key=True, serialize=False)),
                ('requested_quantity', models.IntegerField()),
                ('total_amount', models.IntegerField()),
                ('status', models.CharField(choices=[('Pending', 'Pending'), ('Manager Approved', 'Manager Approved'), ('Finance Pending', 'Finance Pending'), ('Approved', 'Approved'), ('Rejected', 'Rejected')], default='Pending', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.product')),
                ('vendor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vendors.vendor')),
            ],
        ),
        migrations.CreateModel(
            name='PurchaseOrder',
            fields=[
                ('po_id', models.CharField(editable=False, max_length=10, primary_key=True, serialize=False)),
                ('order_quantity', models.IntegerField()),
                ('total_amount', models.IntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('vendor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vendors.vendor')),
                ('pr', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='Inventory.purchaserequest')),
            ],
        ),
    ]
