# Generated by Django 5.2.4 on 2026-03-27 07:03

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Inventory', '0001_initial'),
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Bin',
            fields=[
                ('bin_id', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('capacity', models.IntegerField()),
                ('current_load', models.IntegerField(default=0)),
                ('distance_from_dispatch', models.FloatField()),
                ('pick_count', models.IntegerField(default=0)),
                ('last_picked_at', models.DateTimeField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Rack',
            fields=[
                ('rack_id', models.CharField(max_length=10, primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='Zone',
            fields=[
                ('zone_id', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('zone_type', models.CharField(max_length=20)),
            ],
        ),
        migrations.RemoveField(
            model_name='inventory',
            name='bin_name',
        ),
        migrations.RemoveField(
            model_name='inventory',
            name='last_update',
        ),
        migrations.RemoveField(
            model_name='inventory',
            name='rack_name',
        ),
        migrations.RemoveField(
            model_name='inventory',
            name='shelf_name',
        ),
        migrations.RemoveField(
            model_name='inventory',
            name='zone_name',
        ),
        migrations.AlterField(
            model_name='inventory',
            name='inventory_id',
            field=models.CharField(max_length=10, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='inventory',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.product'),
        ),
        migrations.AddField(
            model_name='inventory',
            name='bin',
            field=models.ForeignKey(default=django.utils.timezone.now, on_delete=django.db.models.deletion.CASCADE, to='Inventory.bin'),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='Shelf',
            fields=[
                ('shelf_id', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('rack', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Inventory.rack')),
            ],
        ),
        migrations.AddField(
            model_name='bin',
            name='shelf',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Inventory.shelf'),
        ),
        migrations.CreateModel(
            name='StockMovement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('movement_type', models.CharField(max_length=20)),
                ('quantity', models.IntegerField()),
                ('previous_stock', models.IntegerField()),
                ('new_stock', models.IntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('bin', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Inventory.bin')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.product')),
            ],
        ),
        migrations.AddField(
            model_name='rack',
            name='zone',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Inventory.zone'),
        ),
    ]
