# Generated by Django 6.0.1 on 2026-03-16 15:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Inventory', '0001_initial'),
        ('vendors', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ASN',
            fields=[
                ('asn_id', models.AutoField(primary_key=True, serialize=False)),
                ('asn_number', models.CharField(max_length=50, unique=True)),
                ('shipment_date', models.DateField()),
                ('expected_arrival_date', models.DateField()),
                ('vehicle_num', models.CharField(max_length=13)),
                ('driver_name', models.CharField(max_length=25)),
                ('driver_phone', models.CharField(max_length=15)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('po', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='asn_po', to='Inventory.purchaseorder')),
                ('vendor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='asn_vendor', to='vendors.vendor')),
            ],
        ),
    ]
