# Generated by Django 5.2.4 on 2026-03-20 03:50

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Inventory', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='grn',
            name='created_by',
        ),
        migrations.AddField(
            model_name='grn',
            name='received_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='grn_received', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='grn',
            name='status',
            field=models.CharField(choices=[('RECEIVED', 'Received by Supervisor'), ('QC_PENDING', 'QC Pending'), ('COMPLETED', 'Completed')], default='RECEIVED', max_length=20),
        ),
    ]
