# Generated by Django 6.0.1 on 2026-03-17 10:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Inventory', '0002_asn'),
    ]

    operations = [
        migrations.AlterField(
            model_name='asn',
            name='asn_id',
            field=models.CharField(editable=False, max_length=10, primary_key=True, serialize=False),
        ),
    ]
