# Generated by Django 6.0.1 on 2026-03-17 11:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Inventory', '0003_alter_asn_asn_id'),
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ASNItem',
            fields=[
                ('asn_item_id', models.CharField(editable=False, max_length=20, primary_key=True, serialize=False)),
                ('expected_quantity', models.IntegerField()),
                ('shipped_quantity', models.IntegerField()),
                ('asn', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='Inventory.asn')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.product')),
            ],
        ),
    ]
