# Generated by Django 6.0.3 on 2026-03-18 05:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Inventory', '0004_asnitem'),
    ]

    operations = [
        migrations.CreateModel(
            name='GRN',
            fields=[
                ('grn_id', models.CharField(editable=False, max_length=10, primary_key=True, serialize=False)),
                ('grn_number', models.CharField(max_length=50, unique=True)),
                ('receipt_date', models.DateField()),
                ('created_at', models.DateField(auto_now_add=True)),
                ('asn', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Inventory.asn')),
                ('po', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Inventory.purchaseorder')),
            ],
        ),
    ]
