# Generated by Django 6.0.3 on 2026-03-18 06:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Inventory', '0005_grn'),
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='GRNItem',
            fields=[
                ('grn_item_id', models.AutoField(primary_key=True, serialize=False)),
                ('expected_quantity', models.IntegerField()),
                ('received_quantity', models.IntegerField()),
                ('accepted_quantity', models.IntegerField()),
                ('rejected_quantity', models.IntegerField()),
                ('qc_status', models.CharField(choices=[('Accepted', 'Accepted'), ('Rejected', 'Rejected')], default='Pending', max_length=15)),
                ('grn', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='Inventory.grn')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.product')),
            ],
        ),
    ]
