# Generated by Django 6.0.3 on 2026-03-18 06:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Inventory', '0006_grnitem'),
    ]

    operations = [
        migrations.AlterField(
            model_name='grnitem',
            name='grn_item_id',
            field=models.CharField(editable=False, max_length=15, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='grnitem',
            name='qc_status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Accepted', 'Accepted'), ('Rejected', 'Rejected')], default='Pending', max_length=15),
        ),
    ]
