# Generated by Django 4.2.25 on 2026-02-25 04:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AgreementMaster',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('agreement_id', models.CharField(max_length=100, unique=True)),
                ('agreement_type', models.CharField(choices=[('SUPPLY', 'Supply'), ('SERVICE', 'Service'), ('STRATEGIC', 'Strategic')], max_length=20)),
                ('effective_date', models.DateField()),
                ('expiry_date', models.DateField()),
                ('renewal_terms', models.TextField(blank=True)),
                ('termination_clause', models.TextField(blank=True)),
                ('governing_law', models.CharField(max_length=200)),
                ('status', models.CharField(choices=[('DRAFT', 'Draft'), ('ACTIVE', 'Active'), ('EXPIRED', 'Expired'), ('TERMINATED', 'Terminated')], default='DRAFT', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='CommercialTerms',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('currency', models.CharField(max_length=10)),
                ('tax_applicable', models.BooleanField(default=True)),
                ('incoterms', models.CharField(max_length=50)),
                ('freight_responsibility', models.CharField(max_length=100)),
                ('insurance_responsibility', models.CharField(max_length=100)),
                ('agreement', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='commercial_terms', to='vendor_agreement.agreementmaster')),
            ],
        ),
        migrations.CreateModel(
            name='Vendor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('vendor_code', models.CharField(max_length=50, unique=True)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(max_length=20)),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='WarrantyTerms',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('warranty_period_days', models.IntegerField()),
                ('replacement_timeline_days', models.IntegerField()),
                ('freight_responsibility', models.CharField(max_length=100)),
                ('scrap_responsibility', models.CharField(max_length=100)),
                ('claim_settlement_days', models.IntegerField()),
                ('agreement', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='warranty_terms', to='vendor_agreement.agreementmaster')),
            ],
        ),
        migrations.CreateModel(
            name='QATerms',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('qa_certificate_required', models.BooleanField(default=False)),
                ('certification_type', models.CharField(blank=True, max_length=200)),
                ('inspection_level', models.CharField(max_length=100)),
                ('quarantine_required', models.BooleanField(default=True)),
                ('holding_cost_per_pallet_per_day', models.DecimalField(decimal_places=2, max_digits=10)),
                ('rtv_allowed', models.BooleanField(default=True)),
                ('agreement', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='qa_terms', to='vendor_agreement.agreementmaster')),
            ],
        ),
        migrations.CreateModel(
            name='PricingSlab',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('min_quantity', models.IntegerField()),
                ('max_quantity', models.IntegerField()),
                ('unit_price', models.DecimalField(decimal_places=2, max_digits=12)),
                ('commercial_terms', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pricing_slabs', to='vendor_agreement.commercialterms')),
            ],
        ),
        migrations.CreateModel(
            name='PerformanceTerms',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sla_on_time_delivery_percentage', models.DecimalField(decimal_places=2, max_digits=5)),
                ('warning_threshold', models.DecimalField(decimal_places=2, max_digits=5)),
                ('suspension_threshold', models.DecimalField(decimal_places=2, max_digits=5)),
                ('penalty_percentage', models.DecimalField(decimal_places=2, max_digits=5)),
                ('agreement', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='performance_terms', to='vendor_agreement.agreementmaster')),
            ],
        ),
        migrations.CreateModel(
            name='PaymentTerms',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('payment_term_days', models.IntegerField()),
                ('advance_percentage', models.DecimalField(decimal_places=2, max_digits=5)),
                ('partial_settlement_allowed', models.BooleanField(default=True)),
                ('credit_period_days', models.IntegerField()),
                ('late_payment_interest', models.DecimalField(decimal_places=2, max_digits=5)),
                ('refund_timeline_days', models.IntegerField()),
                ('agreement', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='payment_terms', to='vendor_agreement.agreementmaster')),
            ],
        ),
        migrations.CreateModel(
            name='DeliveryTerms',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('delivery_window_start', models.TimeField()),
                ('delivery_window_end', models.TimeField()),
                ('expected_lead_time_days', models.IntegerField()),
                ('delay_penalty_percentage', models.DecimalField(decimal_places=2, max_digits=5)),
                ('partial_shipment_allowed', models.BooleanField(default=True)),
                ('asn_mandatory', models.BooleanField(default=True)),
                ('agreement', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='delivery_terms', to='vendor_agreement.agreementmaster')),
            ],
        ),
        migrations.CreateModel(
            name='ComplianceTerms',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gst_compliance_required', models.BooleanField(default=True)),
                ('tds_applicable', models.BooleanField(default=False)),
                ('import_export_compliance', models.BooleanField(default=False)),
                ('insurance_document_required', models.BooleanField(default=True)),
                ('audit_rights_clause', models.BooleanField(default=True)),
                ('agreement', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='compliance_terms', to='vendor_agreement.agreementmaster')),
            ],
        ),
        migrations.AddField(
            model_name='agreementmaster',
            name='vendor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vendor_agreement.vendor'),
        ),
        migrations.CreateModel(
            name='AgreementDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('version', models.IntegerField()),
                ('document', models.FileField(upload_to='agreements/')),
                ('signed', models.BooleanField(default=False)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('agreement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='vendor_agreement.agreementmaster')),
            ],
        ),
    ]
