# Generated by Django 6.0.3 on 2026-03-05 08:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('suppliers', '0002_alter_supplier_email'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='supplier',
            name='supplier_id',
        ),
        migrations.AddField(
            model_name='supplier',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
