# Generated by Django 5.2.4 on 2026-03-03 04:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rbac', '0002_alter_role_name_otp'),
    ]

    operations = [
        migrations.AlterField(
            model_name='role',
            name='name',
            field=models.CharField(choices=[('inventory_manager', 'Inventory Manager'), ('quality_assistant', 'Quality Assistant'), ('admin', 'Admin'), ('manager', 'Manager'), ('supervisor', 'Supervisor')], max_length=50, unique=True),
        ),
    ]
