# Generated by Django 5.2.4 on 2026-03-03 06:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rbac', '0003_alter_role_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='userrole',
            name='is_first_login',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='otp',
            name='purpose',
            field=models.CharField(choices=[('REGISTER', 'Register'), ('RESET_PASSWORD', 'Reset Password'), ('LOGIN', 'Login')], max_length=20),
        ),
    ]
