# Generated by Django 5.2.11 on 2026-03-10 07:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('product_id', models.CharField(editable=False, max_length=10, primary_key=True, serialize=False)),
                ('product_name', models.CharField(max_length=255)),
                ('sku_code', models.CharField(max_length=100, unique=True)),
                ('description', models.TextField()),
                ('category', models.CharField(max_length=100)),
                ('quantity', models.IntegerField()),
                ('ABC', models.CharField(max_length=1)),
                ('VED', models.CharField(max_length=1)),
                ('XYZ', models.CharField(max_length=1)),
                ('unit_price', models.IntegerField()),
                ('re_order', models.IntegerField()),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('vendor_id', models.IntegerField()),
                ('supplier_id', models.IntegerField()),
            ],
        ),
    ]
