# Generated by Django 5.2.11 on 2026-03-24 08:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('supplier', '0001_initial'),
        ('vendors', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('product_id', models.CharField(editable=False, max_length=10, primary_key=True, serialize=False)),
                ('product_name', models.CharField(max_length=255)),
                ('brand_name', models.CharField(max_length=100)),
                ('size', models.CharField(blank=True, default='', max_length=10)),
                ('sku_code', models.CharField(editable=False, max_length=100, unique=True)),
                ('description', models.TextField(blank=True, default='')),
                ('category', models.CharField(max_length=100)),
                ('quantity', models.IntegerField(default=0)),
                ('ABC', models.CharField(max_length=1)),
                ('VED', models.CharField(max_length=1)),
                ('XYZ', models.CharField(max_length=1)),
                ('unit_price', models.IntegerField()),
                ('re_order', models.IntegerField()),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('supplier', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='supplier.supplier')),
                ('vendor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='vendors.vendor')),
            ],
        ),
    ]
