# Generated by Django 5.2.4 on 2026-02-26 08:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('superuser_admin', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='company_name',
        ),
    ]
