# Generated by Django 5.2.4 on 2026-02-26 08:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('superuser_admin', '0002_remove_user_company_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='company_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
